print ("Mohamed")
print ("Febuary 14th 2025")
print (" I am singing up for the replit's 100 days of phython challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happen to be. No excuses for not coding from the middle of a field!")
print ("I am feeling 😛")
print ("You can follow my progress at replit.com/@mohamedm192")
